n1 = int(input("Diga-me um número:"))
n2 = int(input("Diga-me outro número:"))
print(f"A soma de {n1} e {n2}:", (n1 + n2))
print(f"A subtração de {n1} e {n2}:" , (n1 - n2))
print(f"A multiplicação entre {n1} e {n2}:" , (n1 * n2))
print(f"A divisão de {n1} por {n2}:" , (n1 / n2))